[TestCase{
	id='test_r6nTv0Te7egL_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=GET, 
	path='/api/Users/{id}/Attendances/{FromDate}/{ToDate}', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters={id:number=2038863914, FromDate:string=IWt, ToDate:string=GvnGY}, 
	queryParameters={IncludeHolidays:boolean=false, IncludeWeekends:boolean=true, StatusType:number=1692802879}, 
	formParameters=null, 
	bodyParameter='null'
}, TestCase{
	id='test_VpGzjRMqN6vy_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=GET, 
	path='/api/Attendances/{FromDate}/{ToDate}', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters={FromDate:string=, ToDate:string=fBWlGe}, 
	queryParameters={statusType:number=232918915}, 
	formParameters=null, 
	bodyParameter='null'
}, TestCase{
	id='test_bHjBgnZvy8H8_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=PUT, 
	path='/api/Attendances/{id}', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters={id:number=-1927017955}, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='{AttendanceUpsertDto={date="HsLzjpX", startTime="iVC", id=-1937367555, endTime="NePrjXlH", userId=556014141}}'
}, TestCase{
	id='test_DC1IYUuDaJBI_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=GET, 
	path='/api/Users/{id}/Attendances/{FromDate}/{ToDate}/Download', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters={id:number=-844723382, FromDate:string=sFHXn, ToDate:string=cNmi}, 
	queryParameters={IncludeHolidays:boolean=true, IncludeWeekends:boolean=false, StatusType:number=-482047204}, 
	formParameters=null, 
	bodyParameter='null'
}, TestCase{
	id='test_HIjZIZpqdfrB_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=GET, 
	path='/api/Attendances/{FromDate}/{ToDate}/Download', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters={FromDate:string=STH, ToDate:string=qlK}, 
	queryParameters={statusType:number=1287954362}, 
	formParameters=null, 
	bodyParameter='null'
}, TestCase{
	id='test_VXhUdQd7kqAu_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=GET, 
	path='/api/Attendances', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters=null, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='null'
}, TestCase{
	id='test_LKyQQGIFGTII_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=GET, 
	path='/api/Attendances/StatusTypes', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters=null, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='null'
}, TestCase{
	id='test_3JIePo1L4rvF_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=POST, 
	path='/api/Attendances/DataSync/{FromDate}/{ToDate}', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters={FromDate:string=FTBc, ToDate:string=ZGDbWOAT}, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='null'
}, TestCase{
	id='test_fB2pKrd1CRrE_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=POST, 
	path='/api/Authentication/Internal', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters=null, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='{InternalLoginDto={password="PQfSzDpz", email="fAXVq"}}'
}, TestCase{
	id='test_cU3ByarlzJGO_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=POST, 
	path='/api/Authentication/Google', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters=null, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='{GoogleLoginDto={googleTokenID="SWtpz"}}'
}, TestCase{
	id='test_lyhwWkCim3LX_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=GET, 
	path='/Api/ExtraWorkApplications', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters=null, 
	queryParameters={PageSize:number=-1879012076, FromDate:string=nyLX, ApplicationStatus:number=1229359498, ApplicationType:number=2072288616, SearchValue:string=GYtqIa, ToDate:string=TcMVZbbY, PageNumber:number=-276555585}, 
	formParameters=null, 
	bodyParameter='null'
}, TestCase{
	id='test_Mmqu5j5Y9B9t_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=POST, 
	path='/Api/ExtraWorkApplications', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters=null, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='{ExtraWorkApplicationInsertionDto={fromDate="h", adjustmentType=-1006592906, created="VOcqbB", toDate="eLN", supervisorComment="fxPZiBARC", description="i", id=444735153, userId=-635429705, status=-515629191}}'
}, TestCase{
	id='test_h20ZcPdSd8DU_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=GET, 
	path='/Api/ExtraWorkApplications/{id}', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters={id:number=1376131641}, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='null'
}, TestCase{
	id='test_Se2IxggDfQri_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=PUT, 
	path='/Api/ExtraWorkApplications/{id}', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters={id:number=1109789531}, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='{ExtraWorkApplicationUpdateDto={fromDate="b", adjustmentType=1613012280, created="ksk", toDate="m", paid=true, supervisorComment="ib", description="MUhU", id=-912258237, userId=191011620, status=1840160036}}'
}, TestCase{
	id='test_cEcgh593B1vW_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=DELETE, 
	path='/Api/ExtraWorkApplications/{id}', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters={id:number=-557573569}, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='null'
}, TestCase{
	id='test_XwBwVoYD7WFR_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=PATCH, 
	path='/Api/ExtraWorkApplications/Status', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters=null, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='{ExtraWorkStatusChangeDto={supervisorComment="uuFRcfhQ", id=1560451940, status=621153631}}'
}, TestCase{
	id='test_SBVc596pex8p_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=GET, 
	path='/Api/Users/{userId}/ExtraWorkApplications', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters={userId:number=306482568}, 
	queryParameters={PageSize:number=-938993543, FromDate:string=eXBRncR, ApplicationStatus:number=-2122020004, ApplicationType:number=-658466640, SearchValue:string=A, ToDate:string=aYFGUoOThU, PageNumber:number=-1880745285}, 
	formParameters=null, 
	bodyParameter='null'
}, TestCase{
	id='test_MWuJ1HyP7jr7_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=POST, 
	path='/Api/ExtraWorkApplications/DataFilePreview', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters=null, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='null'
}, TestCase{
	id='test_hzu62acTnfpg_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=POST, 
	path='/Api/ExtraWorkApplications/Upload', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters=null, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='null'
}, TestCase{
	id='test_CAHJ4lfzvCX0_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=GET, 
	path='/Api/ExtraWorkApplications/AllStatus', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters=null, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='null'
}, TestCase{
	id='test_AIWBC1Y8rcMv_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=GET, 
	path='/Api/ExtraWorkApplications/AllTypes', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters=null, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='null'
}, TestCase{
	id='test_nFIq9v6sKrgI_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=POST, 
	path='/api/File', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters=null, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='null'
}, TestCase{
	id='test_dK8DIMxiMHJW_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=GET, 
	path='/api/File/{fileName}', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters={fileName:string=BUEIpUEp}, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='null'
}, TestCase{
	id='test_a7LYq4ZBqFp5_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=GET, 
	path='/api/File/ValidationCriteria/{fileType}', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters={fileType:string=ByMYIFiV}, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='null'
}, TestCase{
	id='test_52qEBubcI0oK_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=GET, 
	path='/Api/LeaveApplications', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters=null, 
	queryParameters={PageSize:number=1395002397, FromDate:string=dLOAw, ApplicationStatus:number=-1880843858, ApplicationType:number=1715739689, SearchValue:string=, ToDate:string=utUQi, PageNumber:number=-1237017558}, 
	formParameters=null, 
	bodyParameter='null'
}, TestCase{
	id='test_ru8OyWzhwXaG_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=POST, 
	path='/Api/LeaveApplications', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters=null, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='{LeaveApplicationDto={created="ffekMq", toDate="bAuk", description="cNpuQ", includeSingleHalfDay=false, leaveTypeDisplayName="YIMCzluLuv", leaveSupportingDocumentName="pNdJw", userId=-27091978, fromDate="vRTqM", leaveType=-421394427, supervisorComment="sLWyXEhzDE", leaveStatusDisplayName="iYOACd", id=195170177, status=-12313349}}'
}, TestCase{
	id='test_UVvc6rqi27LC_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=GET, 
	path='/Api/LeaveApplications/{id}', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters={id:number=2095614296}, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='null'
}, TestCase{
	id='test_zK3xUYObV2qk_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=PUT, 
	path='/Api/LeaveApplications/{id}', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters={id:number=-1052501073}, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='{LeaveApplicationDto={created="yIYfqWy", toDate="FUZLgPqFKw", description="", includeSingleHalfDay=true, leaveTypeDisplayName="VDpxZmo", leaveSupportingDocumentName="pdahJ", userId=1631755236, fromDate="WkJih", leaveType=-975037151, supervisorComment="jaupJX", leaveStatusDisplayName="UlSsmZN", id=1939906342, status=107252508}}'
}, TestCase{
	id='test_iQtcIBJcQRMp_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=DELETE, 
	path='/Api/LeaveApplications/{id}', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters={id:number=-379580859}, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='null'
}, TestCase{
	id='test_cPHZBdgEgSjO_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=GET, 
	path='/Api/Users/{userId}/LeaveApplications', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters={userId:number=1285721488}, 
	queryParameters={PageSize:number=-649946316, FromDate:string=kZi, ApplicationStatus:number=587340711, ApplicationType:number=734792087, SearchValue:string=VBlKcSrxoh, ToDate:string=UqL, PageNumber:number=2087100078}, 
	formParameters=null, 
	bodyParameter='null'
}, TestCase{
	id='test_0nAw42xctgr7_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=PATCH, 
	path='/Api/LeaveApplications/Status', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters=null, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='{LeaveStatusChangeDto={id=1252268845, message="Q", status=1045043519}}'
}, TestCase{
	id='test_WLIDTasiKdsP_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=POST, 
	path='/Api/LeaveApplications/DataFilePreview', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters=null, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='null'
}, TestCase{
	id='test_WCN7cJP38GAL_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=POST, 
	path='/Api/LeaveApplications/Upload', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters=null, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='null'
}, TestCase{
	id='test_dKrrz1cjjGmt_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=GET, 
	path='/Api/LeaveApplications/AllStatus', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters=null, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='null'
}, TestCase{
	id='test_KcQIt2cnokbd_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=GET, 
	path='/Api/LeaveApplications/AllTypes', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters=null, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='null'
}, TestCase{
	id='test_pQVK0kEf662b_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=GET, 
	path='/Api/LeaveApplications/LeaveTypes/{userId}', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters={userId:number=1845759193}, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='null'
}, TestCase{
	id='test_xpzL9j0LRvcs_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=GET, 
	path='/Api/Users/{userId}/LeaveBalance/{year}', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters={userId:number=1795202148, year:number=1478531826}, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='null'
}, TestCase{
	id='test_ALCyeiu0cOEQ_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=GET, 
	path='/Api/Users/LeaveBalance/{year}', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters={year:number=1669373238}, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='null'
}, TestCase{
	id='test_xJo80Sk5HYrE_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=GET, 
	path='/Api/Users/LeaveBalance/LeaveStatistics/{year}', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters={year:number=-1763669168}, 
	queryParameters={PageSize:number=-978838211, TeamNames:string=ubFUkDELr, SearchValue:string=bYfQVBUtq, Name:string=HXSkdEhaX, PageNumber:number=627481576}, 
	formParameters=null, 
	bodyParameter='null'
}, TestCase{
	id='test_eR8EhSgu7NRY_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=GET, 
	path='/Api/Users/LeaveBalance/LeaveStatistics/{year}/Download', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters={year:number=1401030999}, 
	queryParameters={PageSize:number=-185720923, TeamNames:string=mh, SearchValue:string=QWSlkove, Name:string=WO, PageNumber:number=-1622930149}, 
	formParameters=null, 
	bodyParameter='null'
}, TestCase{
	id='test_Mkf5bhRXEtga_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=GET, 
	path='/Api/Users/LeaveBalance/Adjust/{year}', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters={year:number=2074351663}, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='null'
}, TestCase{
	id='test_5wNOZqbM93Jd_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=POST, 
	path='/Api/Users/LeaveBalance/DataFilePreview', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters=null, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='null'
}, TestCase{
	id='test_W5eJ6NJMGV8O_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=POST, 
	path='/Api/Users/LeaveBalance/Upload', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters=null, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='null'
}, TestCase{
	id='test_kGKQUx9MC4FK_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=GET, 
	path='/Api/OfficeTimings', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters=null, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='null'
}, TestCase{
	id='test_Tq1rBmkX7lzC_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=POST, 
	path='/Api/OfficeTimings', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters=null, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='{OfficeTimingDto={isDefaultOfficeTiming=false, endDate="QWeH", officeStartTime={milliseconds=-1820320073, hours=-496984860, seconds=1216776344, ticks=-2033971447, minutes=-224387979, days=1212844766}, created="lhiWDUZrb", creatorId=-993519559, creatorName="tobN", lastModifierId=1514180374, lastModifierName="MPscbV", lastModified="i", id=-1365242473, startDate="FIllC"}}'
}, TestCase{
	id='test_34oYP2SmuCIq_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=GET, 
	path='/Api/OfficeTimings/{id}', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters={id:number=2007407402}, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='null'
}, TestCase{
	id='test_rCFo0fFYxk7g_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=PUT, 
	path='/Api/OfficeTimings/{id}', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters={id:number=1098915109}, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='{OfficeTimingDto={isDefaultOfficeTiming=true, endDate="O", officeStartTime={milliseconds=1105857167, hours=262277781, seconds=696520075, ticks=-1694328538, minutes=1602230833, days=1814202692}, created="trvYoF", creatorId=766254241, creatorName="GZLJi", lastModifierId=1065618015, lastModifierName="YBX", lastModified="pcYKoCPq", id=-2147182292, startDate="gKAG"}}'
}, TestCase{
	id='test_mbNzTbNRHP41_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=DELETE, 
	path='/Api/OfficeTimings/{id}', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters={id:number=233053625}, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='null'
}, TestCase{
	id='test_bLexhFdWavBH_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=POST, 
	path='/api/Profiles', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters=null, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='{ProfileUpsertDto={photoFileName="", role="NfBc", displayName="qQCmH", mobileNumber="ASaEJKNb", joiningDate="KpqukZbh", profilePersonalInfoDto={passportNumber="BgZrGRU", nidNumber="", created="vkLqM", creatorId=734268173, creatorName="qUE", dateOfBirth="SQCNGvWB", lastModifierName="dhUJS", bloodGroup="QIErwwuSMo", lastModifierId=-1862136365, lastModified="yujpXiy", id=1459785216, age="tEW", maritalStatus="G"}, userId=-364737916, profileContactInfoDto={created="UgIa", secondaryContactName="DdPifYFCB", creatorId=-838722509, creatorName="pJf", lastModifierName="stI", secondaryContactRelation="C", personalEmail="KRxBXJcdGy", presentAddress="ft", secondaryContactPhoneNo="BKvYfJCY", lastModifierId=-2000287479, permanentAddress="G", lastModified="fgjwhDSWD", id=1323306117}, careerStartDate="N", teamRole="QIfL", designation="C", id=1214548492, slackDisplayName="hBlqNBQb", cvLink="MuM"}}'
}, TestCase{
	id='test_sdQK9yGf9mbq_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=GET, 
	path='/api/Users/{id}/Profile', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters={id:number=-540932091}, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='null'
}, TestCase{
	id='test_gbbgKz825Pta_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=GET, 
	path='/api/Users/{id}/Profile/Short', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters={id:number=1906478656}, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='null'
}, TestCase{
	id='test_oM6dOzOLPdxq_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=GET, 
	path='/api/BloodGroups', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters=null, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='null'
}, TestCase{
	id='test_wThBwYAltThS_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=GET, 
	path='/api/Skills', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters=null, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='null'
}, TestCase{
	id='test_vp0VFcywSTpn_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=GET, 
	path='/api/PublicHolidays/{id}', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters={id:number=1524931052}, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='null'
}, TestCase{
	id='test_nHY4oMpfUaTc_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=PUT, 
	path='/api/PublicHolidays/{id}', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters={id:number=641732487}, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='{PublicHolidayDto={date="lvkuvYLSN", dayName="UHdRET", ticks=-1088025505, name="pzLCWzOnHW", description="", id=88868869, isPast=true}}'
}, TestCase{
	id='test_6m8QTAwLL5m9_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=DELETE, 
	path='/api/PublicHolidays/{id}', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters={id:number=495230714}, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='null'
}, TestCase{
	id='test_fuk0mpUzfoUN_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=GET, 
	path='/api/PublicHolidays', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters=null, 
	queryParameters={year:number=-487974145}, 
	formParameters=null, 
	bodyParameter='null'
}, TestCase{
	id='test_JaXm8imTf6Mu_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=POST, 
	path='/api/PublicHolidays', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters=null, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='{PublicHolidayDto={date="LEdi", dayName="dXYydPpJ", ticks=874941016, name="AYmws", description="OiyGyZhKl", id=-731607206, isPast=true}}'
}, TestCase{
	id='test_GyCqzE2tMAb2_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=POST, 
	path='/api/PublicHolidays/File', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters=null, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='null'
}, TestCase{
	id='test_VV34KXIVd46q_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=GET, 
	path='/Api/RemoteWorkApplications', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters=null, 
	queryParameters={PageSize:number=-1606021857, FromDate:string=yUdjRQOPW, ApplicationStatus:number=-326853270, ApplicationType:number=975178323, SearchValue:string=hcOi, ToDate:string=V, PageNumber:number=528877643}, 
	formParameters=null, 
	bodyParameter='null'
}, TestCase{
	id='test_t14mWlUVhGKS_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=POST, 
	path='/Api/RemoteWorkApplications', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters=null, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='{RemoteWorkApplicationDto={remoteWorkStatusDisplayName="wNCSmBGC", remoteWorkTypeDisplayName="", created="Sik", toDate="", totalNumberOfWorkingDays=1287920175, description="", type=-1215914244, userId=-2115887501, applicant={name=""}, fromDate="aoBCfhXdmp", supervisorComment="fSKsB", id=-513635262, status=2038696077}}'
}, TestCase{
	id='test_WV2HEO5c0VoX_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=GET, 
	path='/Api/Users/{userId}/RemoteWorkApplications/{id}', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters={id:number=-1841128714, userId:number=-415228041}, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='null'
}, TestCase{
	id='test_rrrnnWprvSwE_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=GET, 
	path='/Api/Users/{userId}/RemoteWorkApplications', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters={userId:number=2135072688}, 
	queryParameters={PageSize:number=1528995488, FromDate:string=, ApplicationStatus:number=-569898869, ApplicationType:number=-91971990, SearchValue:string=nrtHzc, ToDate:string=lTfu, PageNumber:number=1658850647}, 
	formParameters=null, 
	bodyParameter='null'
}, TestCase{
	id='test_2CZtm3iOvvMM_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=GET, 
	path='/Api/RemoteWorkApplications/AllApplicationStatus', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters=null, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='null'
}, TestCase{
	id='test_tHnRQFWs5YEa_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=GET, 
	path='/Api/RemoteWorkApplications/Type', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters=null, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='null'
}, TestCase{
	id='test_fF0G0rrMe9ng_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=PUT, 
	path='/Api/RemoteWorkApplications/{id}', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters={id:number=-340879248}, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='{RemoteWorkApplicationDto={remoteWorkStatusDisplayName="IlHSNn", remoteWorkTypeDisplayName="rjqSvXhc", created="kGtlwIHz", toDate="Sdjh", totalNumberOfWorkingDays=-1987704759, description="ueyso", type=-1983870320, userId=1321502750, applicant={name="eSU"}, fromDate="tO", supervisorComment="zATNpJrgX", id=1061555615, status=-859562709}}'
}, TestCase{
	id='test_77P4zoVJEMxV_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=DELETE, 
	path='/Api/RemoteWorkApplications/{id}', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters={id:number=794953925}, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='null'
}, TestCase{
	id='test_Pb4J8qRzcYQF_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=PATCH, 
	path='/Api/RemoteWorkApplications/UpdateStatus', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters=null, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='{RemoteWorkChangeStatusDto={id=-1874458165, message="gCSwn", status=-641721501}}'
}, TestCase{
	id='test_5Exl0B0bf6B7_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=GET, 
	path='/Api/Settings', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters=null, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='null'
}, TestCase{
	id='test_NAEkBXYUrtKD_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=POST, 
	path='/Api/Settings', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters=null, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='{SettingsDto={hrPolicyDocsUrl="zCEEpXHJ", knowledgeSharingSessionsDocsUrl="okFbrVgPr", weeklyWorkFromHomeLimit=-1061020811, created="S", itPolicyDocsUrl="FXmd", allowedCancellationPeriod=1321639486, creatorId=-26338511, creatorName="YCxOuqgYAD", lastModifierName="otq", internalLoginPassword="RFVFkSEom", applicationRequestEmailRecipients="oxLckzdUEo", lastModifierId=392207718, applicationConfirmationEmailRecipients="rSQoiEckTo", lastModified="gKDNvi", id=-1310552704, internalLoginEmail="wcWkvOuW", adminEmail="DnoEPi"}}'
}, TestCase{
	id='test_I8iOP2jvV8PO_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=GET, 
	path='/Api/Settings/Leave', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters=null, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='null'
}, TestCase{
	id='test_AkK6Du696I1h_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=GET, 
	path='/Api/Settings/PolicyDocs', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters=null, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='null'
}, TestCase{
	id='test_DoKjg72VY4BL_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=GET, 
	path='/Api/Settings/Profile', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters=null, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='null'
}, TestCase{
	id='test_o7QGbwoMB1Q3_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=GET, 
	path='/api/Teams', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters=null, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='null'
}, TestCase{
	id='test_rTkueXSEbhf9_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=POST, 
	path='/api/Teams', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters=null, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='{TeamUpsertDto={clientEmail="OubQXHMj", name="CSqlZkVO", teamEmail="cd", id=952110741, isActive=true}}'
}, TestCase{
	id='test_eettdKgn6B3d_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=GET, 
	path='/api/Teams/{id}', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters={id:number=1506184654}, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='null'
}, TestCase{
	id='test_Eqjcl5vjW2Sb_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=PUT, 
	path='/api/Teams/{id}', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters={id:number=-304080463}, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='{TeamUpsertDto={clientEmail="eyXvO", name="aFfirIvtW", teamEmail="IqWdEVlI", id=1090787885, isActive=true}}'
}, TestCase{
	id='test_T6d9PbFsU7B9_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=DELETE, 
	path='/api/Teams/{id}', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters={id:number=48406128}, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='null'
}, TestCase{
	id='test_2P1qzMlNZaWw_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=GET, 
	path='/api/Teams/Member', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters=null, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='null'
}, TestCase{
	id='test_YnurEXdxUoF8_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=GET, 
	path='/api/Teams/{teamId}/Member', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters={teamId:number=-2021224628}, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='null'
}, TestCase{
	id='test_5pNggNCv35IK_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=POST, 
	path='/api/Teams/Members', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters=null, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='null'
}, TestCase{
	id='test_RxIWghiNiwVI_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=POST, 
	path='/api/Teams/GenerateReport', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters=null, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='null'
}, TestCase{
	id='test_PwPKg0797gte_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=GET, 
	path='/api/TotalWorkingDays/{FromDate}/{ToDate}', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters={FromDate:string=DFLgIlu, ToDate:string=qx}, 
	queryParameters={includeHalfDay:boolean=true}, 
	formParameters=null, 
	bodyParameter='null'
}, TestCase{
	id='test_MCtnfZaL4qfW_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=GET, 
	path='/api/Users', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters=null, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='null'
}, TestCase{
	id='test_aLLP3iZxbuwF_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=POST, 
	path='/api/Users', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters=null, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='{UserUpsertDto={attSysUserId=1166182982, isSetLeaveBalanceToZero=false, role=362945271, clientEmail="aGQET", lastWorkingDate="fYbOkECaJw", name="", hideEmail=false, joiningDate="", id=1684937059, isActive=true, email="FejqzkjvuW"}}'
}, TestCase{
	id='test_fQlVehwYxC6U_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=GET, 
	path='/api/Users/Current', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters=null, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='null'
}, TestCase{
	id='test_yCMupqoJ8Rao_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=GET, 
	path='/api/Users/{id}', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters={id:number=-545255609}, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='null'
}, TestCase{
	id='test_sXU6YfEDQcll_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=PUT, 
	path='/api/Users/{id}', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters={id:number=-377090273}, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='{UserUpsertDto={attSysUserId=-716796260, isSetLeaveBalanceToZero=false, role=1988402856, clientEmail="DpYmAkPmS", lastWorkingDate="deGVGNGTaM", name="hC", hideEmail=false, joiningDate="qSRblhbo", id=1877351083, isActive=false, email=""}}'
}, TestCase{
	id='test_M1dKlOxBweAr_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=DELETE, 
	path='/api/Users/{id}', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters={id:number=111578702}, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='null'
}, TestCase{
	id='test_VshBRvWzEJzf_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=GET, 
	path='/api/Users/{id}/Details', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters={id:number=539270060}, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='null'
}, TestCase{
	id='test_M3Yl5ZrdW9yy_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=GET, 
	path='/api/Users/{userId}/TeamMembers', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters={userId:number=1367515104}, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='null'
}, TestCase{
	id='test_N1qX8f69fTQy_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=GET, 
	path='/api/Users/Active/Profiles', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters=null, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='null'
}, TestCase{
	id='test_bbitSiIvT4Lk_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=GET, 
	path='/api/Users/Roles', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters=null, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='null'
}, TestCase{
	id='test_F74iZFwBxqBX_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=GET, 
	path='/api/Users/AttendanceStatistics/{userId}', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters={userId:number=-1734206873}, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='null'
}, TestCase{
	id='test_KgezdsbdnUBm_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=GET, 
	path='/api/Users/LeaveStatistics/{userId}', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters={userId:number=-484041797}, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='null'
}]