[TestCase{
	id='test_KqKcObjdCO4d_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=GET, 
	path='/api/Category', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters=null, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='null'
}, TestCase{
	id='test_kpyssCvFssbQ_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=POST, 
	path='/api/Category', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters=null, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='{Category={name="jznIHAyrq", id=-1396306915}}'
}, TestCase{
	id='test_0x4CYXDDPYAW_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=PUT, 
	path='/api/Category', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters=null, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='{Category={name="", id=-1828681728}}'
}, TestCase{
	id='test_jvKLdPnAY2Zg_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=GET, 
	path='/api/Category/{id}', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters={id:number=-1090380047}, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='null'
}]