[TestCase{
	id='test_vre7LOghcJYW_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=GET, 
	path='/api/Category', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters=null, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='null'
}, TestCase{
	id='test_fcv6OQY0AS96_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=POST, 
	path='/api/Category', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters=null, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='{Category={name="bhDsNZzyqO", id=325885474}}'
}, TestCase{
	id='test_MrFzsp6D1ayN_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=PUT, 
	path='/api/Category', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters=null, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='{Category={name="DC", id=1956645315}}'
}, TestCase{
	id='test_23zWfGlBZLMf_null', 
	faulty=false, 
	faultyReason='none', 
	operationId='null', 
	method=GET, 
	path='/api/Category/{id}', 
	inputFormat='application/json', 
	outputFormat='null', 
	headerParameters=null, 
	pathParameters={id:number=-1839035312}, 
	queryParameters=null, 
	formParameters=null, 
	bodyParameter='null'
}]